SELECT * from teds.teds limit 10;

CREATE TABLE teds.teds_subset AS
SELECT
  CASEID,
  SEX,
  RACE,
  AGE,
  FRSTUSE1,
  PREG,
  NOPRIOR,
  DSMCRIT,
  PSYPROB,
  SERVICES,
  LOS,
  REASON,
  SUB1, 
  FREQ1,
  ROUTE1,
  FREQ_ATND_SELF_HELP, 
  METHUSE,
  BENZFLG,
  TRNQFLG,
  IDU
FROM teds.teds; 

---filter women---

CREATE TEMP TABLE women AS 
  SELECT * FROM `teds.teds_subset`
  WHERE SEX = 2;

SELECT * from women limit 10;

---filter age group---

CREATE TEMP TABLE correct_Age AS 
  SELECT * EXCEPT(SEX) FROM women
  WHERE AGE >= 3 AND AGE <= 8;
  
SELECT * from correct_Age limit 10;   

--determine percentage of nulls in each column
SELECT 
  100 * SUM(CASE WHEN RACE = -9 THEN 1 ELSE 0 END)/COUNT(*) AS RACE,
  100 * SUM(CASE WHEN AGE = -9 THEN 1 ELSE 0 END)/COUNT(*) AS AGE,
  100 * SUM(CASE WHEN FRSTUSE1 = -9 THEN 1 ELSE 0 END)/COUNT(*) AS FRSTUSE1,
  100 * SUM(CASE WHEN PREG = -9 THEN 1 ELSE 0 END)/COUNT(*) AS PREG,
  100 * SUM(CASE WHEN NOPRIOR = -9 THEN 1 ELSE 0 END)/COUNT(*) AS NOPRIOR,
  100 * SUM(CASE WHEN DSMCRIT = -9 THEN 1 ELSE 0 END)/COUNT(*) AS DSMCRIT,
  100 * SUM(CASE WHEN PSYPROB = -9 THEN 1 ELSE 0 END)/COUNT(*) AS PSYPROB,
  100 * SUM(CASE WHEN SERVICES = -9 THEN 1 ELSE 0 END)/COUNT(*) AS SERVICES,
  100 * SUM(CASE WHEN LOS = -9 THEN 1 ELSE 0 END)/COUNT(*) AS LOS,
  100 * SUM(CASE WHEN REASON = -9 THEN 1 ELSE 0 END)/COUNT(*) AS REASON,
  100 * SUM(CASE WHEN SUB1 = -9 THEN 1 ELSE 0 END)/COUNT(*) AS SUB1, 
  100 * SUM(CASE WHEN FREQ1 = -9 THEN 1 ELSE 0 END)/COUNT(*) AS FREQ1,
  100 * SUM(CASE WHEN ROUTE1 = -9 THEN 1 ELSE 0 END)/COUNT(*) AS ROUTE1,
  100 * SUM(CASE WHEN FREQ_ATND_SELF_HELP = -9 THEN 1 ELSE 0 END)/COUNT(*) AS FREQ_ATND_SELF_HELP, 
  100 * SUM(CASE WHEN METHUSE = -9 THEN 1 ELSE 0 END)/COUNT(*) AS METHUSE,
  100 * SUM(CASE WHEN BENZFLG = -9 THEN 1 ELSE 0 END)/COUNT(*) AS BENZFLG,
  100 * SUM(CASE WHEN TRNQFLG = -9 THEN 1 ELSE 0 END)/COUNT(*) AS TRNQFLG,
  100 * SUM(CASE WHEN IDU = -9 THEN 1 ELSE 0 END)/COUNT(*) AS IDU
FROM correct_Age;

--removal of nulls--
CREATE TEMP TABLE remove_Nulls AS 
  SELECT * FROM correct_Age
  WHERE 
    FRSTUSE1 != -9 AND
    DSMCRIT != -9 AND
    PSYPROB != -9 AND
    SUB1 != -9 AND 
    FREQ1 != -9 AND
    ROUTE1 != -9 AND
    FREQ_ATND_SELF_HELP != -9 AND 
    METHUSE != -9 AND
    IDU != -9; 
   
 SELECT * from remove_Nulls limit 10; 

---check again how many missings
SELECT 
  100 * SUM(CASE WHEN RACE = -9 THEN 1 ELSE 0 END)/COUNT(*) AS RACE,
  100 * SUM(CASE WHEN AGE = -9 THEN 1 ELSE 0 END)/COUNT(*) AS AGE,
  100 * SUM(CASE WHEN FRSTUSE1 = -9 THEN 1 ELSE 0 END)/COUNT(*) AS FRSTUSE1,
  100 * SUM(CASE WHEN PREG = -9 THEN 1 ELSE 0 END)/COUNT(*) AS PREG,
  100 * SUM(CASE WHEN NOPRIOR = -9 THEN 1 ELSE 0 END)/COUNT(*) AS NOPRIOR,
  100 * SUM(CASE WHEN DSMCRIT = -9 THEN 1 ELSE 0 END)/COUNT(*) AS DSMCRIT,
  100 * SUM(CASE WHEN PSYPROB = -9 THEN 1 ELSE 0 END)/COUNT(*) AS PSYPROB,
  100 * SUM(CASE WHEN SERVICES = -9 THEN 1 ELSE 0 END)/COUNT(*) AS SERVICES,
  100 * SUM(CASE WHEN LOS = -9 THEN 1 ELSE 0 END)/COUNT(*) AS LOS,
  100 * SUM(CASE WHEN REASON = -9 THEN 1 ELSE 0 END)/COUNT(*) AS REASON,
  100 * SUM(CASE WHEN SUB1 = -9 THEN 1 ELSE 0 END)/COUNT(*) AS SUB1, 
  100 * SUM(CASE WHEN FREQ1 = -9 THEN 1 ELSE 0 END)/COUNT(*) AS FREQ1,
  100 * SUM(CASE WHEN ROUTE1 = -9 THEN 1 ELSE 0 END)/COUNT(*) AS ROUTE1,
  100 * SUM(CASE WHEN FREQ_ATND_SELF_HELP = -9 THEN 1 ELSE 0 END)/COUNT(*) AS FREQ_ATND_SELF_HELP, 
  100 * SUM(CASE WHEN METHUSE = -9 THEN 1 ELSE 0 END)/COUNT(*) AS METHUSE,
  100 * SUM(CASE WHEN BENZFLG = -9 THEN 1 ELSE 0 END)/COUNT(*) AS BENZFLG,
  100 * SUM(CASE WHEN TRNQFLG = -9 THEN 1 ELSE 0 END)/COUNT(*) AS TRNQFLG,
  100 * SUM(CASE WHEN IDU = -9 THEN 1 ELSE 0 END)/COUNT(*) AS IDU
FROM remove_Nulls;


SELECT * from remove_Nulls limit 100; 

-------- replace nulls with mode --------
  CREATE TEMP TABLE modes AS
    SELECT RACE, 
    PREG,
    NOPRIOR
    FROM remove_Nulls
    WHERE RACE !=-9
    and PREG != -9
    and NOPRIOR != -9
    GROUP BY RACE, 
    PREG,
    NOPRIOR
    ORDER BY COUNT(*) DESC
    LIMIT 1;


SELECT * from modes;

---JOIN TABLES
CREATE TEMP TABLE replaced_Nulls AS
 SELECT
  c.CASEID,
  CASE WHEN c.RACE = -9 THEN m.race ELSE c.RACE END AS RACE,
  c.AGE,
  CASE WHEN c.PREG= -9 THEN m.preg ELSE c.PREG END AS PREG,
  CASE WHEN c.NOPRIOR= -9 THEN m.noprior ELSE c.NOPRIOR END AS NOPRIOR,
  C.FRSTUSE1,
  c.DSMCRIT,
  c.PSYPROB,
  c.SERVICES,
  c.LOS,
  c.REASON,
  c.SUB1,
  c.FREQ1,
  c.ROUTE1,
  c.FREQ_ATND_SELF_HELP,
  c.METHUSE,
  c.BENZFLG,
  c.TRNQFLG,
  c.IDU
  FROM remove_Nulls c, modes m;

SELECT * from replaced_Nulls limit 10;

--BINARIZATION

CREATE TEMP TABLE binarized AS
SELECT 
  CASEID,
  RACE,
  AGE,
  FRSTUSE1,
  CASE WHEN PREG = 2 THEN 0 ELSE 1 END AS PREG,
  NOPRIOR,
  DSMCRIT,
  CASE WHEN PSYPROB = 2 THEN 0 ELSE 1 END AS PSYPROB,
  SERVICES,
  CASE 
    WHEN LOS <=30 THEN 0
    WHEN LOS IN (31, 32) THEN 1
    WHEN LOS IN (33,34,35) THEN 2
    WHEN LOS IN (36,37) THEN 3
  END AS LOS_PERIOD,
  REASON,
  SUB1,
  FREQ1,
  ROUTE1,
  FREQ_ATND_SELF_HELP,
  CASE WHEN METHUSE = 2 THEN 0 ELSE 1 END AS METHUSE,
  BENZFLG,
  TRNQFLG,
  IDU
FROM replaced_Nulls;

--- < 30 = 1-30 days
--- 31,32 = 31-60 days
--- 33-35 = 61-180 days
--- 36-37 = 181-365+ days

select * from binarized limit 10; 


CREATE TABLE teds.final AS
  SELECT * EXCEPT (METHUSE, BENZFLG, TRNQFLG, IDU, LOS_PERIOD), 
  CASE WHEN METHUSE = 1 OR
  BENZFLG = 1 OR
  TRNQFLG = 1 OR
  IDU = 1
  THEN 1 ELSE 0 END AS HIGH_RISK
  FROM binarized;

CREATE TABLE teds.final_los AS
  SELECT * 
  FROM binarized;
